name: build-oci-image

run-name: Build OCI Image for GoLang binary

on:
  push:
    branches: ['master']
    tags: ['v*']
  #pull_request:
  #  branches: ['main']

env:
  GH_REGISTRY: ghcr.io # Github Container Registry
  FULL_IMAGE_NAME: ${{ github.repository }} # full image name: owner/image

jobs:
  build-oci-image:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-22.04

    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: read # for actions/checkout
      packages: write # for OCI build
      #id-token: write # for requesting OIDC JWT from 3rd party

    steps:

      # checkout
      - name: Check out repository code
        uses: actions/checkout@v4

      # docker hub credentials
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          #registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # tags and labels
      - name: Extract metadata (tags, labels) for image ${{ env.FULL_IMAGE_NAME }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
          # push to both docker hub and Github Container Registry
          images: |
            ${{ env.FULL_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=pr
            type=ref,event=branch
            # in addition to full semantic version (x.y.z) would also create (x.y)
            #type=semver,pattern={{major}}.{{minor}}


      # build OCI image and push to registries (Docker Hub and Github Container Registry)
      - name: build and push docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

